# Generated by Django 5.2.7 on 2025-11-11 20:22

import azura.mvc.music.models.library
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('path', models.FileField(upload_to=azura.mvc.music.models.library.get_upload_path)),
                ('artists', models.ManyToManyField(to='music.artist')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.library')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
