# Generated by Django 5.2.7 on 2025-11-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='path',
            new_name='file',
        ),
    ]
