# Generated by Django 5.2.9 on 2025-12-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
        ('music', '0002_rename_path_song_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_global', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.user')),
                ('songs', models.ManyToManyField(blank=True, to='music.song')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
