# Generated by Django 5.2.9 on 2025-12-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
    ]
