# Generated by Django 5.2.9 on 2025-12-08 19:20

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='music.song'),
        ),
    ]
