# Generated by Django 5.2.9 on 2025-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
        ('music', '0007_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('owner', 'name')},
        ),
    ]
