# Generated by Django 6.0.4 on 2026-04-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
        ('music', '0008_alter_playlist_name_alter_playlist_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
